# Generated by Django 4.1.7 on 2023-04-08 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='appointment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_specialty', to='clinics.appointmenttype'),
        ),
    ]
