# Generated by Django 4.1.7 on 2023-04-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_appointment_appointment_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
